### ISSUE TITLE
information of NTIRE 2024 LLIE dataset 

### ISSUE THREAD

**Issue by lucasta1** [caiyuanhao1998/Retinexformer#113]
Hello.

In the "Prepare Dataset" content, you described that "NTIRE 2024", and I found the "NTIRE Challenge on Low Light Image Enhancement" paper here; https://arxiv.org/pdf/2404.14248v1 . In that paper, they mentioned that there are 230 pairs of training data and 35 for validation. However, in your link of "mini_val", there are only 15 images. How did you manage the dataset?

I'd be happy if you tell me about this. Thank you.

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest.

the minival dataset are split from the 230 training pairs and the 35 validation pairs are not used in this repo because when I released the code of NTIRE part, the validation data were not released. People still competed in the NTIRE challenge. You can directly use the original training and testing sets or just follow our repo.

If you find our repo useful, please help us star it, thank you :)
