### ISSUE TITLE
he results I trained are much lower than the actual results in the paper.

### ISSUE THREAD

**Issue by WM-XIAO** [caiyuanhao1998/Retinexformer#26]
Hello, I have two questions. The first is: the results I trained are much lower than the actual results in the paper. Would the author please share a pre-trained model that has been well trained? What is your training equipment and environment, and what is the software version?The second is: in the paper, you said iterations were 250,000, but why is total_iter: 150,000 in the code?

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest.

In fact, we have shared all the pre-trained models in every dataset:
Please download our models from [Baidu Disk](https://pan.baidu.com/s/13zNqyKuxvLBiQunIxG_VhQ?pwd=cyh2) (code: cyh2) or [Google Drive](https://drive.google.com/drive/folders/1ynK5hfQachzc8y96ZumhkPPDXzHJwaQV?usp=drive_link). Put them in the folder `pretrained_weights`

We also provide detailed training logs on every dataset. Please feel free to check our training logs from [Baidu Disk](https://pan.baidu.com/s/16NtLba_ANe3Vzji-eZ1xAA?pwd=cyh2) (code: cyh2) or [Google Drive](https://drive.google.com/drive/folders/1HU_wEn_95Hakxi_ze-pS6Htikmml5MTA?usp=sharing).

We suggest you to train the models on a single RTX 8000 GPU with our suggested environment in the `README.md` file.

As for the iterations, because different datasets have different scales and training pairs, the required iterations are different
